#!/bin/bash

open_network() {
	/usr/bin/gnome-control-center --class=floating_window network
}

case $BLOCK_BUTTON in
    1) open_network ;; # left click
    2) open_network ;; # middle click
    3) open_network ;; # right click
esac

result=$(nmcli -t -f type,state,connection d | egrep "^(tun|tap):connected" | awk -F':' '{ print $3 }')
[[ -z $result ]] && echo 'VPN: off' || echo "VPN: on"

